### ISSUE TITLE
Make it easy to gather again with the same configuration

### ISSUE THREAD

**Issue by nirs** [nirs/kubectl-gather#51]
If we need to gather again due to running old version of kubectl gather or some other issue, we need to construct the gather command again. This can be done by looking at the gathered data:

```
$ ls gather-2024-08-18/*/namespaces
gather-2024-08-18/c01-mdr-c1/namespaces:
openshift-dr-ops  openshift-dr-system  openshift-operators  vmware1  vmware2

gather-2024-08-18/c01-mdr-c2/namespaces:
openshift-dr-ops  openshift-dr-system  openshift-operators  vmware1  vmware2

gather-2024-08-18/c01-mdr-hub/namespaces:
openshift-dr-ops  openshift-operators
```

And constructing the command:

```
kubectl gather --contexts c01-mdr-hub,c01-mdr-c1,c01-mdr-c2 -n openshift-dr-ops,openshift-dr-system,openshift-operators,vmware1,vmware2 -d gather-2024-08-20
```

It would be easier if we would log log the complete command used in the gather.log:

```
2024-08-20T18:51:22.408+0300	INFO	gather	Running "kubectl gather --contexts c01-mdr-hub,c01-mdr-c1,c01-mdr-c2 -n openshift-dr-ops,openshift-dr-system,openshift-operators,vmware1,vmware2 -d gather-2024-08-20"
```

Another way, keep a yaml file with the gather info:

```yaml
contexts:
  - c01-mdr-hub
  - c01-mdr-c1
  - c01-mdr-c2
namesapces:
  - openshift-dr-ops
  - openshift-dr-system
  - openshift-operators
  - vmware1
  - vmware2
directory: gather-2024-08-20
```

And teach kubectl-gather to load that file:

```
kubectl gather -f gather.yaml
```

The values from the file can be used as defaults for the command line options, so you can override them using the command line:

```
kubectl gather -f gather.yaml -d overridden-directory
```

This can also be useful for developers and testers that want to run the same gather command multiple times, for example to compare the state before and after operations. The gather option can also be kept in git for reproducible gather operations.
