### ISSUE TITLE
Gather logs from initContainers

### ISSUE THREAD

**Issue by nirs** [nirs/kubectl-gather#6]
They are typically tiny but may help to debug issues if the init container failed.

Example from rook-ceph-osd pod:

```yaml
  initContainerStatuses:
  - containerID: containerd://f701074bf1946a1d46725be5c00f448c63c3d0f44b3a7f360dfac40bccb469dd
    image: quay.io/ceph/ceph:v18
    imageID: quay.io/ceph/ceph@sha256:e7b0c424bb65f4de966af67d0a1bf6a2e9d4cbf787371f642453588104298720
    lastState: {}
    name: activate
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://f701074bf1946a1d46725be5c00f448c63c3d0f44b3a7f360dfac40bccb469dd
        exitCode: 0
        finishedAt: "2024-05-11T21:29:18Z"
        reason: Completed
        startedAt: "2024-05-11T21:29:15Z"
  - containerID: containerd://9d68ec8cacf471992ea75000acbe67611e52f04608ac5a82ed922d84e0c8ec02
    image: quay.io/ceph/ceph:v18
    imageID: quay.io/ceph/ceph@sha256:e7b0c424bb65f4de966af67d0a1bf6a2e9d4cbf787371f642453588104298720
    lastState: {}
    name: expand-bluefs
    ready: true
    restartCount: 0
    started: false
    state:
      terminated:
        containerID: containerd://9d68ec8cacf471992ea75000acbe67611e52f04608ac5a82ed922d84e0c8ec02
        exitCode: 0
        finishedAt: "2024-05-11T21:29:20Z"
        reason: Completed
        startedAt: "2024-05-11T21:29:19Z"
```
